build-job:
  docker:
    - image: circleci/node:8.1.3
  working_directory: /
  steps:
    - run:
        name: Install Yarn
        command: yarn
    - run:
        name: Compile Node
        command: yarn run build
    - save_cache:
        key: dependency-cache
        paths:
          - ~/.cache/yarn

deploy-job:
  docker:
    - image: circleci/node:8.1.3
  working_directory: /
  steps:
    - run:
        name: Run setup script
        command: bash .circleci/setup-heroku.sh
    - add_ssh_keys:
        fingerprints:
          - "7c:a8:eb:e8:75:74:ea:06:66:6d:e6:c8:a0:31:13:e9"
    - run:
        name: Deploy Master to Heroku
        command: |
          git push --force git@heroku.com:pacex-dev.git HEAD:refs/heads/dev2

 workflows:
   version: 2
   build-deploy:
     jobs:
       - build-job
       - deploy-job:
           requires:
             - build-job
           filters:
             branches:
               only: dev2
